- name: Get system architecture
  command: dpkg --print-architecture
  register: arch_res
  changed_when: false
  check_mode: no

- name: Get latest nginx-build version
  uri:
    url: https://api.github.com/repos/cubicdaiya/nginx-build/releases/latest
    body_format: json
  register: nginx_latest_release

- name: Assert that tag_name is available
  assert:
    that:
      - nginx_latest_release.json is defined
      - nginx_latest_release.json.tag_name is defined
      - nginx_latest_release.json.tag_name is string
    fail_msg: "Failed to get tag_name from GitHub API response. Check API rate limits or network connectivity."

- name: Download nginx-build
  get_url:
    url: "https://github.com/cubicdaiya/nginx-build/releases/download/{{ nginx_latest_release.json.tag_name }}/nginx-build-linux-{{ arch_res.stdout }}-{{ nginx_latest_release.json.tag_name | replace('v', '') }}.tar.gz"
    dest: /tmp/nginx-build-linux.tar.gz

- name: Extract nginx-build
  unarchive:
    src: /tmp/nginx-build-linux.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy to /usr/local/bin/
  become: yes
  copy:
    src: /tmp/nginx-build
    dest: /usr/local/bin/
    remote_src: yes
    mode: "0755"
