name: Ansible CI

on:
  pull_request:
    paths:
      - "ansible/**"
      - ".github/workflows/ansible.yml"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create Vault Password File
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_password_private
        working-directory: ansible

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i test site.yml

      - name: Run Ansible playbook in check mode
        run: |
          cd ansible
          ansible-playbook --check -i test site.yml
